### ISSUE TITLE
Can't create new entry in general ledger

### ISSUE THREAD

**Issue by gerardgn** [DoliCloud/DoliDroid#11]
Hello,

In the menu: accounting/ general ledger, when i want to create a new entry, the buttons doesn't appear.

Best regards.

**Comment by eldy** [comment]
Can you provide a screenshot ?
What is your Dolibarr version ?

**Comment by gerardgn** [comment]
My Dolibarr version is 17.0.2.
![Dolidroid_entry_general_ledger](https://github.com/DoliCloud/DoliDroid/assets/66369417/0f4c0156-e03a-44e8-a27c-c999ed13496a)

**Comment by eldy** [comment]
This is a bug in v17.0 branch.
https://github.com/Dolibarr/dolibarr/commit/bd77c11d416c26de407d133897741d484be6a493
